### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by Ahmad-AlShalabi** [ulikoehler/cv_algorithms#4]
ERROR: Command errored out with exit status 1:

   command: 'c:\users\userb\anaconda3\envs\tabletrainnet_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USERb~1\\AppData\\Local\\Temp\\pip-install-juo3afv7\\cv-algorithms_c69eb1f14e86421ba8e084ddba8405c2\\setup.py'"'"'; __file__='"'"'C:\\Users\\USERB~1\\AppData\\Local\\Temp\\pip-install-juo3afv7\\cv-algorithms_c69eb1f14e86421ba8e084ddba8405c2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USREB~1\AppData\Local\Temp\pip-wheel-qghofp8x'
       cwd: C:\Users\USERB~1\AppData\Local\Temp\pip-install-juo3afv7\cv-algorithms_c69eb1f14e86421ba8e084ddba8405c2\

  LINK : warning LNK4044: unrecognized option '/g'; ignored
  LINK : error LNK2001: unresolved external symbol PyInit__cv_algorithms
  build\temp.win-amd64-3.6\Release\src\_cv_algorithms.cp36-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
  ----------------------------------------
  ERROR: Failed building wheel for cv-algorithms

**Comment by ulikoehler** [comment]
Thanks for reporting this. I don't have too much experience with compiling python modules on Windows, but the issue is clearly
```
LINK : error LNK2001: unresolved external symbol PyInit__cv_algorithms
```
which is strange since we use CFFI in order to build and access the external module. I will try to reproduce the issue on my computer.

**Comment by Ahmad-AlShalabi** [comment]
Thanks for replying and helping,

I'm excited to run the OTR on my computer, I hope this issue will be  fixed soon

**Comment by ulikoehler** [comment]
I'm sorry this took more than a year to fix. Today I did some rework on the code to make it Windows/MSVC-compatible. For me, on Windows, it works fine now. Could you please verify and (if it doesn't work) re-open the issue?
